# Generated by Django 4.1 on 2022-08-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InicioCabaña', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocabaña',
            name='Cocina',
        ),
    ]
