# Generated by Django 4.1 on 2022-08-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioCabaña', '0002_remove_registrocabaña_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocabaña',
            name='Cocina',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=50, null=True, verbose_name='Cocina'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Baño',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Baño'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Botiquin',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Botiquin'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Calefaccion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Calefaccion'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Extinguidor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Extinguidor'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Telefono',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Televisor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Televisor'),
        ),
        migrations.AlterField(
            model_name='registrocabaña',
            name='Wifi',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10, verbose_name='Wifi'),
        ),
    ]
