# Generated by Django 4.1 on 2022-08-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioCabaña', '0003_registrocabaña_cocina_alter_registrocabaña_baño_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocabaña',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
