# Generated by Django 4.1 on 2022-08-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioCabaña', '0004_registrocabaña_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Titulo')),
                ('email', models.CharField(max_length=254, verbose_name='Correo')),
                ('comentario', models.TextField(null=True, verbose_name='Descripcion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Archivos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Registro de Archivos',
                'verbose_name_plural': 'Registro de Archivos',
                'ordering': ['id'],
            },
        ),
    ]
