# Generated by Django 4.1 on 2022-08-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioCabaña', '0005_archivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'ordering': ['-created'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='archivos',
            name='updated',
        ),
        migrations.AddField(
            model_name='archivos',
            name='CURP',
            field=models.CharField(max_length=100, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='Direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='Edad',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='Medicamento',
            field=models.CharField(max_length=100, null=True, verbose_name='Medicamentos a Tomar'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='NombrePaciente',
            field=models.CharField(max_length=150, null=True, verbose_name='Nombre del Paciente'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='Sexo',
            field=models.CharField(max_length=100, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='Telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos', verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion'),
        ),
    ]
