# Generated by Django 4.1 on 2022-08-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioCabaña', '0007_alter_archivos_options_remove_archivos_curp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocabaña',
            name='oferta',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Oferta'),
        ),
    ]
